SELECT * FROM hr.employees; 

SELECT MAX(SALARY) FROM hr.employees;

SELECT MAX(SALARY) - MIN(SALARY) FROM hr.employees;

SELECT JOB_ID, AVG(SALARY) AS averagy_salary FROM hr.employees
GROUP BY JOB_ID
ORDER BY averagy_salary DESC;

SELECT SUM(SALARY) FROM hr.employees;

SELECT ROUND(MAX(SALARY),2) AS maior_salario,
	ROUND(MIN(SALARY),2) AS menor_salario,
    ROUND(SUM(SALARY),2) AS total_salarios,
    ROUND(AVG(SALARY),2) AS media_salarios
FROM hr.employees;

SELECT COUNT(JOB_ID) FROM hr.employees
WHERE JOB_ID = 'IT_PROG';

SELECT JOB_ID, SUM(SALARY) FROM hr.employees
GROUP BY JOB_ID;

SELECT JOB_ID, SUM(SALARY) FROM hr.employees
GROUP BY JOB_ID
HAVING JOB_ID = 'IT_PROG';

SELECT JOB_ID, AVG(SALARY) AS media FROM hr.employees
WHERE JOB_ID <> 'IR_PROG'
GROUP BY JOB_ID
ORDER BY media DESC;

SELECT AVG(SALARY), COUNT(*) AS func
FROM hr.employees
GROUP BY DEPARTMENT_ID
HAVING func > 10;

SET SQL_SAFE_UPDATES = 0;
UPDATE hr.employees
SET PHONE_NUMBER = REPLACE(PHONE_NUMBER, '515', '777')
WHERE PHONE_NUMBER LIKE '515%';
SET SQL_SAFE_UPDATES = 1;

SELECT * FROM hr.employees
WHERE CHAR_LENGTH(FIRST_NAME) >= 8;

SELECT EMPLOYEE_ID, FIRST_NAME, YEAR(HIRE_DATE)
FROM hr.employees;

SELECT EMPLOYEE_ID, FIRST_NAME, DAY(HIRE_DATE)
FROM hr.employees;

SELECT EMPLOYEE_ID, FIRST_NAME, MONTH(HIRE_DATE)
FROM hr.employees;

SELECT UCASE(FIRST_NAME) FROM hr.employees;

SELECT LAST_NAME, HIRE_DATE
FROM hr.employees
WHERE HIRE_DATE LIKE '1987-07%';

SELECT FIRST_NAME,
	   LAST_NAME,
       DATEDIFF(CURRENT_DATE(), HIRE_DATE)
FROM hr.employees;
